# Generated by Django 4.1.1 on 2022-10-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
