# Generated by Django 4.1.1 on 2022-10-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_share_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
