# Generated by Django 4.1.1 on 2022-10-23 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0008_share_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='likes',
            field=models.ManyToManyField(related_name='share_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
